import numpy as np
# result = np.array([1,3,5,7,9,2,4,6,8])
# print(result)
# for i in result:
#     print(i)
# numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# deneme1 = numpy_array
# deneme2 = numpy_array.reshape(5,2)
# deneme3 = numpy_array.reshape(2,5)
# print(deneme1.sum(axis = 0))
# print(deneme3)
# print(deneme3.sum(axis=0))
# print(deneme3.sum(axis=1))
# numpy_array = np.arange(10,step = 3)
# print(numpy_array)
# deneme = numpy_array.reshape(5,2)
# print(deneme)
# print("*"*20)
# secme = deneme[3,1]
# print(secme)
# deneme = numpy_array.reshape(5,2)
# print(deneme)
# print("*"*20)
# print(deneme[::-1])
# print(np.ones((3,3)))
# print(np.eye(3))
# deneme = numpy_array.reshape(5,2)
# print(np.concatenate([deneme,deneme],axis = 1))
# print(numpy_array.sum())
# print(numpy_array.mean())
# print(np.median(numpy_array))
# print(numpy_array.argmax())
# print(numpy_array.argmin())
# print(numpy_array.sum(axis = 0))
# print(numpy_array.sum(axis = 1))
# print(numpy_array.min())
# print(numpy_array.max())
# print(numpy_array1)
# print(numpy_array1+numpy_array1)
# print(numpy_array1-1)
# print(numpy_array1*numpy_array1)
# print(numpy_array1/numpy_array1)
# print(np.sqrt(numpy_array1))
# print(numpy_array1**2)
# numpy_array = np.array([0,1,2,3,4,5,6,7,8,9])
# numpy_array = numpy_array.reshape(5,2)
# numpy_array2 = numpy_array.reshape(5,2)
# print(np.dot(numpy_array2,numpy_array1))
# print(numpy_array)
# print(numpy_array.T)
# numpy_array = np.array([0,15,30,45,60,75,90])
# result = np.cos(numpy_array)
# print(result)
# numpy_array1 = numpy_array1.reshape(3,3)
# numpy_array2 = np.random.randint(10,100,9)
# numpy_array2 = numpy_array2.reshape(3,3)
# print(numpy_array2)
# result = np.vstack((numpy_array1,numpy_array2))
# print(result)
# for i in numpy_array:
#     if i > 50:
#         print(f"{i} 50den büyük")
#     else:
#         print(f"{i} 50den küçük")
# numpy_array = np.random.randint(10,100,6)
# print(numpy_array)
# result = numpy_array % 2 == 0
# print(result)
# print(numpy_array[result == False])


