# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dizilladesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 769)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableDiziler = QtWidgets.QTableWidget(self.centralwidget)
        self.tableDiziler.setGeometry(QtCore.QRect(30, 20, 641, 691))
        self.tableDiziler.setColumnCount(2)
        self.tableDiziler.setObjectName("tableDiziler")
        self.tableDiziler.setRowCount(0)
        self.tableDiziler.horizontalHeader().setDefaultSectionSize(239)
        self.btnTop100 = QtWidgets.QPushButton(self.centralwidget)
        self.btnTop100.setGeometry(QtCore.QRect(690, 80, 93, 28))
        self.btnTop100.setObjectName("btnTop100")
        self.btnEniyi = QtWidgets.QPushButton(self.centralwidget)
        self.btnEniyi.setGeometry(QtCore.QRect(690, 210, 93, 28))
        self.btnEniyi.setObjectName("btnEniyi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnTop100.setText(_translate("MainWindow", "IMDB top 100"))
        self.btnEniyi.setText(_translate("MainWindow", "En İyiler"))
