# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imdbListedesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableListe = QtWidgets.QTableWidget(self.centralwidget)
        self.tableListe.setGeometry(QtCore.QRect(30, 30, 561, 781))
        self.tableListe.setColumnCount(3)
        self.tableListe.setObjectName("tableListe")
        self.tableListe.setRowCount(0)
        self.cbSecenek = QtWidgets.QComboBox(self.centralwidget)
        self.cbSecenek.setGeometry(QtCore.QRect(670, 220, 191, 51))
        self.cbSecenek.setObjectName("cbSecenek")
        self.btnOnayla = QtWidgets.QPushButton(self.centralwidget)
        self.btnOnayla.setGeometry(QtCore.QRect(700, 420, 161, 51))
        self.btnOnayla.setObjectName("btnOnayla")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnOnayla.setText(_translate("MainWindow", "Onayla"))
