# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kmhtompsdesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 301)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnmpstokmh = QtWidgets.QPushButton(self.centralwidget)
        self.btnmpstokmh.setGeometry(QtCore.QRect(90, 180, 101, 31))
        self.btnmpstokmh.setObjectName("btnmpstokmh")
        self.btnkmhtomps = QtWidgets.QPushButton(self.centralwidget)
        self.btnkmhtomps.setGeometry(QtCore.QRect(520, 180, 93, 28))
        self.btnkmhtomps.setObjectName("btnkmhtomps")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(61, 61, 171, 87))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtMps = QtWidgets.QLineEdit(self.widget)
        self.txtMps.setObjectName("txtMps")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtMps)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lblKmh = QtWidgets.QLabel(self.widget)
        self.lblKmh.setText("")
        self.lblKmh.setObjectName("lblKmh")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lblKmh)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(471, 61, 171, 87))
        self.widget1.setObjectName("widget1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget1)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtKmh = QtWidgets.QLineEdit(self.widget1)
        self.txtKmh.setObjectName("txtKmh")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtKmh)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lblMps = QtWidgets.QLabel(self.widget1)
        self.lblMps.setText("")
        self.lblMps.setObjectName("lblMps")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lblMps)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnmpstokmh.setText(_translate("MainWindow", "mps to kmh"))
        self.btnkmhtomps.setText(_translate("MainWindow", "kmh to mps"))
        self.label.setText(_translate("MainWindow", "MPS"))
        self.label_3.setText(_translate("MainWindow", "KMH"))
        self.label_2.setText(_translate("MainWindow", "KMH"))
        self.label_4.setText(_translate("MainWindow", "MPS"))
