# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpeedTestdesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 273)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnDownload = QtWidgets.QPushButton(self.centralwidget)
        self.btnDownload.setGeometry(QtCore.QRect(70, 50, 93, 28))
        self.btnDownload.setObjectName("btnDownload")
        self.btnUpload = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpload.setGeometry(QtCore.QRect(340, 50, 93, 28))
        self.btnUpload.setObjectName("btnUpload")
        self.lblDownload = QtWidgets.QLabel(self.centralwidget)
        self.lblDownload.setGeometry(QtCore.QRect(70, 130, 121, 51))
        self.lblDownload.setText("")
        self.lblDownload.setObjectName("lblDownload")
        self.lblUpload = QtWidgets.QLabel(self.centralwidget)
        self.lblUpload.setGeometry(QtCore.QRect(340, 130, 131, 51))
        self.lblUpload.setText("")
        self.lblUpload.setObjectName("lblUpload")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnDownload.setText(_translate("MainWindow", "Download"))
        self.btnUpload.setText(_translate("MainWindow", "Upload"))
