# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\trigodesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSec = QtWidgets.QPushButton(self.centralwidget)
        self.btnSec.setGeometry(QtCore.QRect(320, 260, 241, 81))
        self.btnSec.setObjectName("btnSec")
        self.lblSonuc = QtWidgets.QLabel(self.centralwidget)
        self.lblSonuc.setGeometry(QtCore.QRect(390, 430, 171, 71))
        self.lblSonuc.setObjectName("lblSonuc")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 30, 491, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtAci = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtAci.setObjectName("txtAci")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtAci)
        self.groupTri = QtWidgets.QGroupBox(self.centralwidget)
        self.groupTri.setGeometry(QtCore.QRect(60, 150, 791, 80))
        self.groupTri.setTitle("")
        self.groupTri.setObjectName("groupTri")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupTri)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 781, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.HorizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalLayout.setObjectName("HorizontalLayout")
        self.rbSin = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rbSin.setObjectName("rbSin")
        self.HorizontalLayout.addWidget(self.rbSin)
        self.rbCos = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rbCos.setObjectName("rbCos")
        self.HorizontalLayout.addWidget(self.rbCos)
        self.rbTan = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rbTan.setObjectName("rbTan")
        self.HorizontalLayout.addWidget(self.rbTan)
        self.rbCot = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rbCot.setObjectName("rbCot")
        self.HorizontalLayout.addWidget(self.rbCot)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSec.setText(_translate("MainWindow", "Seç"))
        self.lblSonuc.setText(_translate("MainWindow", "Sonuç:"))
        self.label.setText(_translate("MainWindow", "Açı:"))
        self.rbSin.setText(_translate("MainWindow", "Sinüs"))
        self.rbCos.setText(_translate("MainWindow", "Cosinüs"))
        self.rbTan.setText(_translate("MainWindow", "Tanjant"))
        self.rbCot.setText(_translate("MainWindow", "Cotanjant"))
