# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vkidesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblSonuc = QtWidgets.QLabel(self.centralwidget)
        self.lblSonuc.setGeometry(QtCore.QRect(10, 230, 501, 121))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.lblSonuc.setFont(font)
        self.lblSonuc.setTextFormat(QtCore.Qt.AutoText)
        self.lblSonuc.setObjectName("lblSonuc")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 321, 181))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtKilo = QtWidgets.QLineEdit(self.widget)
        self.txtKilo.setObjectName("txtKilo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtKilo)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtBoy = QtWidgets.QLineEdit(self.widget)
        self.txtBoy.setObjectName("txtBoy")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtBoy)
        self.btnHesapla = QtWidgets.QPushButton(self.widget)
        self.btnHesapla.setObjectName("btnHesapla")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnHesapla)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblSonuc.setText(_translate("MainWindow", "Sonuç"))
        self.label.setText(_translate("MainWindow", "Kilo"))
        self.label_2.setText(_translate("MainWindow", "Boy"))
        self.btnHesapla.setText(_translate("MainWindow", "Hesapla"))
